# Generated by Django 4.0.3 on 2022-03-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('company', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('amount_products', models.IntegerField()),
            ],
        ),
    ]
